### PR TITLE
U.S spelling of Organization

### PR DESCRIPTION
**Pull request by kodypeterson**

### CODE REVIEW

**Comment by kodypeterson** [comment]
Maybe saying "Correct spelling" is not the right way, but I believe "Organization" is the more commonly used spelling of the word...

**Comment by GLMeece** [comment]
The spelling @kodypeterson suggests is correct for the U.S. only. I can appreciate that since I'm in the U.S. as well, but unless/until this project is internationali**z**ed, you may have to live with your own fork.

**Comment by imjacobclark** [comment]
I'm in the UK so 'organisation' is the correct spelling over here. 

Happy to accept a PR to introduce internationalisation.

**Comment by imjacobclark** [comment]
Closing

**Pull request closed without merging**
